ocaml:
	ocamlopt -o fta-test nums.cmxa all.mli all.ml main.ml
	ocamlopt -p -o fta-test-prof nums.cmxa all.mli all.ml main.ml
	strip fta-test

ml: ocaml

haskell: 
	ghc-6.2 -fglasgow-exts -o fta-test-hs all.hs main.hs
	strip fta-test-hs

hs: haskell
